# services/store_service/capabilities/store_info_normalization/constants.py

# Maps known retailer variants to canonical retailer names and inferred store types.
# Preserves the legacy retailer-key behavior used by Store Service locators.
RETAILER_KEY_MAP: dict[str, str] = {
    "kroger": "kroger",
    "king soopers": "kroger",
    "ralphs": "kroger",
    "fred meyer": "kroger",
    "smith's": "kroger",
    "fry's": "kroger",
    "publix": "publix",
    "safeway": "safeway",
    "albertsons": "albertsons",
    "vons": "albertsons",
    "jewel": "jewelosco",
    "jewel-osco": "jewelosco",
    "acme": "acmemarkets",
    "tom thumb": "tomthumb",
    "randalls": "randalls",
    "shaw's": "shaws",
    "shaws": "shaws",
    "star market": "starmarket",
    "haggen": "haggen",
    "carrs": "carrsqc",
    "balducci": "balduccis",
    "kings food": "kingsfoodmarkets",
    "market street": "shopmarketstreet",
    "united supermarket": "shopunitedsupermarkets",
    "smart & final": "smart_and_final",
    "smart and final": "smart_and_final",
    "walmart": "walmart",
    "wal-mart": "walmart",
    "target": "target",
    "whole foods": "whole_foods",
    "trader joe": "trader_joes",
    "aldi": "aldi",
    "lidl": "lidl",
    "costco": "costco",
    "sam's club": "sams_club",
    "sams club": "sams_club",
    "h-e-b": "heb",
    "heb": "heb",
    "meijer": "meijer",
    "stop & shop": "stop_and_shop",
    "stop and shop": "stop_and_shop",
    "giant": "giant",
    "wegmans": "wegmans",
    "harris teeter": "harris_teeter",
    "food lion": "food_lion",
    "sprouts": "sprouts",
    "winn-dixie": "winn_dixie",
    "winndixie": "winn_dixie",
    "dollar general": "dollar_general",
    "family dollar": "family_dollar",
    "cvs": "cvs",
    "walgreens": "walgreens",
    "rite aid": "rite_aid",
}


DEFAULT_RETAILER_NORMALIZATION_MAP: dict[str, tuple[str, str | None]] = {
    "walmart": ("Walmart", None),
    "wal mart": ("Walmart", None),
    "walmart supercenter": ("Walmart", "Supercenter"),
    "walmart super center": ("Walmart", "Supercenter"),
    "walmart neighborhood market": ("Walmart", "Neighborhood Market"),
    "walmart neighborhood": ("Walmart", "Neighborhood Market"),
    "walmart business center": ("Walmart", "Business Center"),
    "walmart fuel center": ("Walmart", "Fuel Center"),
    "walmart discount": ("Walmart", "Discount"),
    "cvs": ("CVS Pharmacy", None),
    "cvs pharmacy": ("CVS Pharmacy", None),
    "walgreens": ("Walgreens", None),
    "target": ("Target", None),
    "aldi": ("Aldi", None),
    "costco": ("Costco", None),
    "costco wholesale": ("Costco", None),
    "kroger": ("Kroger", None),
    "dollar tree": ("Dollar Tree", None),
    "dollartree": ("Dollar Tree", None),
    "family dollar": ("Family Dollar", None),
    "familydollar": ("Family Dollar", None),
    "petsmart": ("PetSmart", None),
    "petco": ("Petco", None),
    "best buy": ("Best Buy", None),
    "bestbuy": ("Best Buy", None),
    "ulta": ("Ulta Beauty", None),
    "ulta beauty": ("Ulta Beauty", None),
    "trader joe's": ("Trader Joe's", None),
    "trader joe s": ("Trader Joe's", None),
    "traderjoes": ("Trader Joe's", None),
    "sam's club": ("Sam's Club", None),
    "sam s club": ("Sam's Club", None),
    "sams club": ("Sam's Club", None),
    "publix": ("Publix", None),
    "food lion": ("Food Lion", None),
    "foodlion": ("Food Lion", None),
    "safeway": ("Safeway", None),
    "smart and final": ("Smart & Final", None),
    "smart final": ("Smart & Final", None),
    "smart & final": ("Smart & Final", None),
    "sprouts farmers market": ("Sprouts Farmers Market", None),
    "grocery outlet": ("Grocery Outlet", None),
    "bj's wholesale club": ("BJ's Wholesale Club", None),
    "bj s wholesale club": ("BJ's Wholesale Club", None),
    "bjs wholesale club": ("BJ's Wholesale Club", None),
    "whole foods market": ("Whole Foods Market", None),
    "wholefoodsmarket": ("Whole Foods Market", None),
    "stop and shop": ("Stop & Shop", None),
    "stop shop": ("Stop & Shop", None),
    "winn dixie": ("Winn-Dixie", None),
    "7 eleven": ("7-Eleven", None),
    "seven eleven": ("7-Eleven", None),
    "seveneleven": ("7-Eleven", None),
    "7eleven": ("7-Eleven", None),
}